name: Parse links

on:
  workflow_dispatch:  
#   schedule: 
#     cron: "0 0 * * *"   
#     tz: Asia/Shanghai  

jobs:
  parse_links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Get link.txt  
      run: |
        cat .github/workflows/link.txt > links.txt   
    - name: Parse links 
      run: |
        config={}  
        while read link; do    
          content=$(curl -s $link)    
          config["$link"]=$content   
        done < links.txt
        echo "$config" > config.json
    - name: Upload artifact  
      uses: actions/upload-artifact@v2
      with:
        name: config.json
        path: config.json 
  save_to_repo:
    runs-on: ubuntu-latest  
    needs: parse_links  
    steps: 
    - name: Download artifact  
      uses: actions/download-artifact@v2
      with:
        name: config.json
    - name: Save to repo  
      run: |  
        git clone git@github.com:ei0ch/Self-use.git 
        mkdir -p Self-use/Self-use%20software/TV/  
        cp config.json Self-use/Self-use%20software/TV/    
        cd Self-use
        - name: Setup git identity    
          run: |
            git config --local user.email "ei0ch@github.com"
            git config --local user.name "ei0ch"
        git tag v1.0.0
        git push git@github.com:ei0ch/Self-use.git v1.0.0 
