yaml
name: Parse links

on:
  workflow_dispatch:  
#   schedule: 
#     cron: "0 0 * * *"   
#     tz: Asia/Shanghai  

jobs:
  parse_links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  
    - name: Get link.txt  
      run: |
        cat .github/workflows/link.txt > links.txt   
    - name: Parse links 
      run: |
        config={}  
        while read link; do    
          content=$(curl -s $link)    
          config["$link"]=$content   
        done < links.txt
        echo "$config" > config.json
    - name: Upload artifact  
      uses: actions/upload-artifact@v2
      with:
        name: config.json
        path: config.json 
  
  save_to_repo:
    runs-on: ubuntu-latest
    needs: parse_links  # 需要依赖parse_links job
    steps: 
    - name: Download artifact  
      uses: actions/download-artifact@v2
      with:
        name: config.json
    - name: Save to repo  
      run: |
        git clone https://github.com/ei0ch/Self-use # 克隆仓库
        cp config.json Self-use/Self-use%20software/TV/ # 复制到指定路径
        cd Self-use
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add config.json"  # 提交更新
        git push  # 推送更新
