name: Parse links

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: '0 19 * * *' # 每天凌晨3点(中国上海时间)自动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2

    - name: Get links
      run: |
        links=`cat link.txt`

    - name: Parse links
      run: | 
        for link in $links; do
          curl $link > temp.html
          cat temp.html >> config.json
        done

    - name: Commit config.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add config.json
        git commit -m "Update config.json" -a
    
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: ${{ github.ref }}
        force: true
