name: Parse links

on:
  workflow_dispatch:  


jobs:
  parse_links:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2 
    - name: Get link.txt  
      run: |
        cat .github/workflows/link.txt > links.txt 
    - name: Parse links  
      run: |
        config={}
        while read link; do
          content=$(curl -s $link)
          config["$link"]=$content
        done < links.txt
        echo "$config" > links.json
    - name: Upload artifact  
      uses: actions/upload-artifact@v2  
      with:
        name: links.json
        path: links.json
        
  commit_files:
    needs: parse_links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clone repo
      run: git clone https://github.com/ei0ch/Self-use.git 
    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master 
        file_pattern: links.json
        directory: Self-use/Self-use software/TV/ 
        commit_message: Add config file
