name: Parse links

on:
  workflow_dispatch:  
#   schedule: 
#     cron: "0 0 * * *"   # 每天上午0点 
#     tz: Asia/Shanghai
    
jobs:
  parse_links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checkout代码
    - name: Get link.txt  
      run: |
        cat .github/workflows/link.txt > links.txt   # 读取link.txt到links.txt
    - name: Parse links
      run: |
        config={}  # 定义空config
        while read link; do   # 遍历links.txt中的每一行
          content=$(curl -s $link)   # 访问链接获取内容
          config["$link"]=$content   # 将链接和内容添加到config中
        done < links.txt
        echo "$config" > config.json  # 输出config到config.json文件中
