name: Spider

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SCHEDULED_TIME: ${{ github.event.schedule }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install nokogiri
        gem install open-uri

    - name: Run spider
      run: ruby spider.rb
