name: Spider

on:
  workflow_dispatch:
    branches: [ main ]
#  schedule:
#    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SCHEDULED_TIME: ${{ github.event.schedule }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install nokogiri
        gem install open-uri

    - name: Run spider
      run: ruby spider.rb

    - name: Copy tvconfig.json to folder
      run: |
        mkdir -p Self-use/Self-use\ software/TV/config
        cp tvconfig.json Self-use/Self-use\ software/TV/config/
